package ec.edu.epn.contratos.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-07-20T18:39:39.784-05:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://entities.cpa.epn.edu.ec/", name = "GeneracionContratosWS")
@XmlSeeAlso({ObjectFactory.class})
public interface GeneracionContratosWS {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosGeneralRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosGeneralResponse")
    @RequestWrapper(localName = "contratosGeneral", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosGeneral")
    @WebMethod
    @ResponseWrapper(localName = "contratosGeneralResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosGeneralResponse")
    public byte[] contratosGeneral(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/enviarActividadesRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/enviarActividadesResponse")
    @RequestWrapper(localName = "enviarActividades", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.EnviarActividades")
    @WebMethod
    @ResponseWrapper(localName = "enviarActividadesResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.EnviarActividadesResponse")
    public byte[] enviarActividades(
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/informeOcasionalInvitadoRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/informeOcasionalInvitadoResponse")
    @RequestWrapper(localName = "informeOcasionalInvitado", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.InformeOcasionalInvitado")
    @WebMethod
    @ResponseWrapper(localName = "informeOcasionalInvitadoResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.InformeOcasionalInvitadoResponse")
    public byte[] informeOcasionalInvitado(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/componerIDPedidoRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/componerIDPedidoResponse")
    @RequestWrapper(localName = "componerIDPedido", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ComponerIDPedido")
    @WebMethod
    @ResponseWrapper(localName = "componerIDPedidoResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ComponerIDPedidoResponse")
    public java.lang.String componerIDPedido();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosPNRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosPNResponse")
    @RequestWrapper(localName = "contratosPN", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosPN")
    @WebMethod
    @ResponseWrapper(localName = "contratosPNResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosPNResponse")
    public byte[] contratosPN(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosAyRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosAyResponse")
    @RequestWrapper(localName = "contratosAy", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosAy")
    @WebMethod
    @ResponseWrapper(localName = "contratosAyResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosAyResponse")
    public byte[] contratosAy(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/informeOcasionalHonorarioRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/informeOcasionalHonorarioResponse")
    @RequestWrapper(localName = "informeOcasionalHonorario", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.InformeOcasionalHonorario")
    @WebMethod
    @ResponseWrapper(localName = "informeOcasionalHonorarioResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.InformeOcasionalHonorarioResponse")
    public byte[] informeOcasionalHonorario(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosPXRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosPXResponse")
    @RequestWrapper(localName = "contratosPX", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosPX")
    @WebMethod
    @ResponseWrapper(localName = "contratosPXResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosPXResponse")
    public byte[] contratosPX(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/informeTecnicoServiciosOcasionalesRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/informeTecnicoServiciosOcasionalesResponse")
    @RequestWrapper(localName = "informeTecnicoServiciosOcasionales", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.InformeTecnicoServiciosOcasionales")
    @WebMethod
    @ResponseWrapper(localName = "informeTecnicoServiciosOcasionalesResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.InformeTecnicoServiciosOcasionalesResponse")
    public byte[] informeTecnicoServiciosOcasionales(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosInvitadosRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosInvitadosResponse")
    @RequestWrapper(localName = "contratosInvitados", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosInvitados")
    @WebMethod
    @ResponseWrapper(localName = "contratosInvitadosResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosInvitadosResponse")
    public byte[] contratosInvitados(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosIHRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosIHResponse")
    @RequestWrapper(localName = "contratosIH", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosIH")
    @WebMethod
    @ResponseWrapper(localName = "contratosIHResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosIHResponse")
    public byte[] contratosIH(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosOcacional1TCRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosOcacional1TCResponse")
    @RequestWrapper(localName = "contratosOcacional1TC", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosOcacional1TC")
    @WebMethod
    @ResponseWrapper(localName = "contratosOcacional1TCResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosOcacional1TCResponse")
    public byte[] contratosOcacional1TC(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosOcacional1TPRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosOcacional1TPResponse")
    @RequestWrapper(localName = "contratosOcacional1TP", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosOcacional1TP")
    @WebMethod
    @ResponseWrapper(localName = "contratosOcacional1TPResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosOcacional1TPResponse")
    public byte[] contratosOcacional1TP(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/enviarCargaRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/enviarCargaResponse")
    @RequestWrapper(localName = "enviarCarga", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.EnviarCarga")
    @WebMethod
    @ResponseWrapper(localName = "enviarCargaResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.EnviarCargaResponse")
    public byte[] enviarCarga(
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosTDPRequest", output = "http://entities.cpa.epn.edu.ec/GeneracionContratosWS/contratosTDPResponse")
    @RequestWrapper(localName = "contratosTDP", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosTDP")
    @WebMethod
    @ResponseWrapper(localName = "contratosTDPResponse", targetNamespace = "http://entities.cpa.epn.edu.ec/", className = "ec.edu.epn.contratos.webservices.ContratosTDPResponse")
    public byte[] contratosTDP(
        @WebParam(name = "pedido", targetNamespace = "")
        byte[] pedido,
        @WebParam(name = "carga", targetNamespace = "")
        byte[] carga,
        @WebParam(name = "actividades", targetNamespace = "")
        byte[] actividades
    );
}
